
server:
  port: 9030
  
  
spring:
  datasource:
    url: jdbc:mariadb://revy-senpai.c7otdgsixoyh.us-east-2.rds.amazonaws.com:3306/project2db
    username: project2user
    password:  mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: false
    hibernate:
      ddl-auto: create
      