# yaml satnds for (Yaml ain't Markup Lamguage')


server:
  port: 9037


spring:
  datasource:
    url: jdbc:mariadb://revy-senpai.c7otdgsixoyh.us-east-2.rds.amazonaws.com:3306/springbootdb
    username: springbootuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: create
